// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"go-dyndns/addrproviders"
	"go-dyndns/log"
	"go-dyndns/updater"
	"net/http"
)

// Injectors from wire.go:

func CreateClient(logger log.Logger) (*DynDnsClient, error) {
	clientClientConfig, err := loadConfig()
	if err != nil {
		return nil, err
	}
	providerType := clientClientConfig.IpProvider
	httpClient := _wireClientValue
	addressProvider, err := addrproviders.CreateProvider(providerType, httpClient)
	if err != nil {
		return nil, err
	}
	updaterUpdater, err := updater.CreateUpdater(httpClient)
	if err != nil {
		return nil, err
	}
	dynDnsClient, err := newDynDnsClient(clientClientConfig, logger, addressProvider, updaterUpdater)
	if err != nil {
		return nil, err
	}
	return dynDnsClient, nil
}

var (
	_wireClientValue = http.DefaultClient
)
