// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"go-dyndns/addrproviders"
	"go-dyndns/updater"
)

// Injectors from wire.go:

func CreateClient() (*DynDnsClient, error) {
	clientClientConfig, err := loadConfig()
	if err != nil {
		return nil, err
	}
	providerType := clientClientConfig.IpProvider
	addressProvider, err := addrproviders.CreateProvider(providerType)
	if err != nil {
		return nil, err
	}
	updaterUpdater, err := updater.CreateUpdater()
	if err != nil {
		return nil, err
	}
	dynDnsClient, err := newDynDnsClient(clientClientConfig, addressProvider, updaterUpdater)
	if err != nil {
		return nil, err
	}
	return dynDnsClient, nil
}
