// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package addrproviders

// Injectors from wire.go:

func createWebProvider() (*webProvider, error) {
	webProviderConfig, err := loadWebProviderConfig()
	if err != nil {
		return nil, err
	}
	addrprovidersWebProvider := newWebProvider(webProviderConfig)
	return addrprovidersWebProvider, nil
}

func createFritzBoxProvider() (*fritzBoxProvider, error) {
	addrprovidersFritzBoxConfig, err := loadFritzBoxConfig()
	if err != nil {
		return nil, err
	}
	addrprovidersFritzBoxProvider := newFritzBoxProvider(addrprovidersFritzBoxConfig)
	return addrprovidersFritzBoxProvider, nil
}
