// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package addrproviders

import (
	"net/http"
)

// Injectors from wire.go:

func createWebProvider() (*webProvider, error) {
	webProviderConfig, err := loadWebProviderConfig()
	if err != nil {
		return nil, err
	}
	httpClient := _wireClientValue
	addrprovidersWebProvider := newWebProvider(webProviderConfig, httpClient)
	return addrprovidersWebProvider, nil
}

var (
	_wireClientValue = http.DefaultClient
)

func createFritzBoxProvider() (*fritzBoxProvider, error) {
	addrprovidersFritzBoxConfig, err := loadFritzBoxConfig()
	if err != nil {
		return nil, err
	}
	httpClient := _wireClientValue
	addrprovidersFritzBoxProvider := newFritzBoxProvider(addrprovidersFritzBoxConfig, httpClient)
	return addrprovidersFritzBoxProvider, nil
}
