// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-dyndns/client"
	"go-dyndns/updater"
)

// Injectors from wire.go:

func Init() (*client.DynDnsClient, error) {
	clientConfig, err := client.LoadConfig()
	if err != nil {
		return nil, err
	}
	updaterConfig, err := updater.LoadConfig()
	if err != nil {
		return nil, err
	}
	updaterUpdater := updater.NewDynDnsUpdater(updaterConfig)
	dynDnsClient, err := client.NewDynDnsClient(clientConfig, updaterUpdater)
	if err != nil {
		return nil, err
	}
	return dynDnsClient, nil
}
