// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package log

// Injectors from wire.go:

func CreateLogger() (Logger, error) {
	logLoggerConfig, err := loadConfig()
	if err != nil {
		return nil, err
	}
	logWriterLogger := createDefaultWriterLogger(logLoggerConfig)
	return logWriterLogger, nil
}
