// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package updater

import (
	"go-dyndns/util"
)

// Injectors from wire.go:

func CreateUpdater(httpClient util.HttpClient) (Updater, error) {
	updaterDynDnsUpdaterConfig, err := loadDynDnsConfig()
	if err != nil {
		return nil, err
	}
	updaterDynDnsUpdater := newDynDnsUpdater(updaterDynDnsUpdaterConfig, httpClient)
	return updaterDynDnsUpdater, nil
}
