// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package updater

import (
	"net/http"
)

// Injectors from wire.go:

func CreateUpdater() (Updater, error) {
	updaterDynDnsUpdaterConfig, err := loadDynDnsConfig()
	if err != nil {
		return nil, err
	}
	httpClient := _wireClientValue
	updaterDynDnsUpdater := newDynDnsUpdater(updaterDynDnsUpdaterConfig, httpClient)
	return updaterDynDnsUpdater, nil
}

var (
	_wireClientValue = http.DefaultClient
)
