// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package updater

// Injectors from wire.go:

func CreateUpdater() (Updater, error) {
	updaterDynDnsUpdaterConfig, err := loadDynDnsConfig()
	if err != nil {
		return nil, err
	}
	updaterDynDnsUpdater := newDynDnsUpdater(updaterDynDnsUpdaterConfig)
	return updaterDynDnsUpdater, nil
}
